name: "publish"

on:
    push:
        branches:
            - master

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "macos-latest"
                      target: aarch64-apple-darwin
                    - platform: "macos-latest"
                      target: x86_64-apple-darwin
                    - platform: "ubuntu-22.04"
                      target: x86_64-unknown-linux-gnu
                    - platform: "windows-latest"
                      target: x86_64-pc-windows-msvc
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Extract version from package.json (or Cargo.toml)
              id: get_version
              shell: pwsh
              run: |
                  $VERSION = (Get-Content package.json | ConvertFrom-Json).version
                  if (-not $VERSION) {
                    $VERSION = (Select-String -Pattern 'version = "([^"]+)"' -Path Cargo.toml).Matches.Groups[1].Value
                  }
                  Write-Output "Version is $VERSION"
                  echo "version=$VERSION" >> $env:GITHUB_ENV

            - name: Create Tag
              run: |
                  git tag "v${{ env.version }}"
                  git push origin "v${{ env.version }}"

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Install dependencies (Ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Frontend dependencies
              run: npm install

            - name: Rustup add target
              run: rustup target add ${{ matrix.target }}

            - name: Build Tauri App
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: v${{ env.version }}
                  releaseName: "v${{ env.version }}"
                  releaseDraft: true
                  prerelease: false
                  args: -t ${{ matrix.target }}

            - name: Create GitHub Release
              run: |
                  gh release create v${{ env.version }} target/${{ matrix.target }}/release/bundle/* --title "Release v${{ env.version }}" --notes "Release notes for version v${{ env.version }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
